spring.application.name=CineTicket

#spring.datasource.url=jdbc:h2:mem:cineticket
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=password

spring.datasource.url=jdbc:postgresql://localhost:5432/cineticket
spring.datasource.username=postgres
spring.datasource.password=Mritunjay@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# JWT Configuration
jwt.secret=c7f3a9b2e4d6f8a1c3e5b7d9f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c7f3a9b2e4d6f8a1c3e5b7d9f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0
jwt.expiry.minutes=600