spring.application.name=CineTicket

spring.datasource.url=jdbc:postgresql://localhost:5432/cineticket
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your_jwt_secret_minimum_64_bytes_here

server.port=8080
